[workspace]
authors = ["Giovanni Dejan"]
channels = ["conda-forge"]
name = "pixi-jupyter-notebook"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
lab = "jupyter lab --no-browser"

[system-requirements]
cuda = "12.0"

[dependencies]
python = ">=3.13"
pytorch-gpu = "*"
numpy = ">=2.3.5,<3"
scipy = ">=1.16.3,<2"
torchvision = ">=0.24.1,<0.25"
jupyterlab = ">=4.5.0,<5"
matplotlib = ">=3.10.8,<4"
pandas = ">=2.3.3,<3"
pixi-kernel = ">=0.7.1,<0.8"
scikit-learn = ">=1.7.2,<2"
pip = ">=25.3,<26"
opencv = ">=4.12.0,<5"
seaborn = ">=0.13.2,<0.14"
