[workspace]
authors = ["Giovanni Dejan"]
channels = ["conda-forge"]
name = "pixi-jupyter-notebook"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12.0"

[dependencies]
pytorch-gpu = "*"
numpy = ">=2.3.5,<3"
scipy = ">=1.16.3,<2"
torchvision = ">=0.24.1,<0.25"
jupyterlab = ">=4.5.0,<5"
matplotlib = ">=3.10.8,<4"
pandas = ">=2.3.3,<3"
pixi-kernel = ">=0.7.1,<0.8"
